(source "gnu" "http://elpa.gnu.org/packages/")
(source "org" "http://orgmode.org/elpa/")
(source "melpa" "http://melpa.milkbox.net/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(depends-on "ac-js2")
(depends-on "auto-complete")
(depends-on "cask")
(depends-on "coffee-mode")
(depends-on "dash")
(depends-on "epl")
(depends-on "exec-path-from-shell")
(depends-on "f")
(depends-on "findr")
(depends-on "flx-ido")
(depends-on "flycheck")
(depends-on "flycheck-hdevtools")
(depends-on "flycheck-ledger")
(depends-on "fringe-helper")
(depends-on "fuzzy")
(depends-on "ghc")
(depends-on "git")
(depends-on "git-commit-mode")
(depends-on "git-gutter")
(depends-on "git-gutter-fringe")
(depends-on "git-rebase-mode")
(depends-on "graphviz-dot-mode")
(depends-on "haskell-mode")
(depends-on "helm")
(depends-on "helm-css-scss")
(depends-on "helm-flycheck")
(depends-on "helm-git")
(depends-on "helm-git-grep")
(depends-on "helm-ls-git")
;;(depends-on "helm-open-gthub")
(depends-on "helm-projectile")
(depends-on "highlight-parentheses")
(depends-on "htmlize")
(depends-on "ido-yes-or-no")
(depends-on "inf-ruby")
(depends-on "inflections")
(depends-on "javap-mode")
(depends-on "js2-mode")
(depends-on "jump")
(depends-on "ledger-mode")
(depends-on "less-css-mode")
(depends-on "litable")
(depends-on "magit")
(depends-on "magit-gh-pulls")
(depends-on "magit-hub")
(depends-on "markdown-mode")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "pandoc-mode")
(depends-on "paredit")
(depends-on "pivotal-tracker")
(depends-on "pkg-info")
(depends-on "plantuml-mode")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "rhtml-mode")
(depends-on "rinari")
(depends-on "ruby-compilation")
(depends-on "rvm")
(depends-on "s")
(depends-on "smart-mode-line")
(depends-on "smart-parens")
(depends-on "smex")
(depends-on "wakatime-mode")
(depends-on "yaml-mode")

;; lisps
(depends-on "ac-nrepl")
(depends-on "cider")
(depends-on "clj-refactor")
(depends-on "clojurescript-mode")

;; org
;; (depends-on "org")
;; (depends-on "org-plus-contrib")
;; (depends-on "ox-reveal")

(depends-on "clojure-test-mode")
(depends-on "clojure.tools.namespace.repl")
(depends-on "expectations")
(depends-on "nrepl")
(depends-on "nrepl-eval-sexp-fu")
(depends-on "nrepl-eval-sexp-fu")
(depends-on "smartparens")

(depends-on "solarized-theme")
(depends-on "zenburn-theme")
